### ISSUE TITLE
Support ROCm-enabled MPI library and OSU benchmark

### ISSUE THREAD

**Issue by paklui** [rocmsys/RET#12]
**Is your feature request related to a problem? Please describe.**
The Open MPI in OS distro does not support GPU for P2P communication, which requires ROCm-enabled UCX that needs to be build separately. See #11

**Describe the solution you'd like**
To build Open MPI support with UCX for ROCm described here: https://github.com/openucx/ucx/wiki/Build-and-run-ROCM-UCX-OpenMPI. Also include OSU Micro Benchmark for sanity testing.

**Describe alternatives you've considered**
ROCm software repository will ultimately provide this ROCm-enabled MPI support in the future, to provide binary distribution of Open MPI and UCX for each distribution, because building it each time can take half hour.

**Additional context**
[ret.log](https://github.com/rocmsys/RET/files/3998707/ret.log)

**Comment by reger-men** [comment]
Pull request has been merged!
