### ISSUE TITLE
TensorFlow install does not install required Paramiko package

### ISSUE THREAD

**Issue by nsburbank** [rocmsys/RET#15]
TensorFlow install using 'sudo /.ret install tensorflow' fails during verification step, due to Paramiko not being installed.

Paramiko is listed as a prerequisite at https://github.com/reger-men/tensorflow_benchmark/blob/master/README.md#pre-requirement, but the RET installer does not automatically install this package. 

This was observed on a freshly imaged Ubuntu 18.04 system

**Comment by reger-men** [comment]
Thank you, @nsburbank for reporting this!

Could you please confirm whether the problem still exists or not?

**Comment by nsburbank** [comment]
Seems to be working fine now for me.
