### ISSUE TITLE
Tensorflow benchmarks doesn't work

### ISSUE THREAD

**Issue by emoon** [rocmsys/RET#8]
**System information**
- Ubuntu 18.04 LTS
- 4x Vega Frontier Edition
- AMD Ryzen Threadripper 2950X  and 32 GB of RAM

**Describe the bug**
Unable to run step 8/12 of the installation script

**To Reproduce:**
1. Do a clean Ubuntu 18.04 installation
2. Run `sudo ./ret install rocm`
3. Reboot
4. Run `sudo ./ret install tensorflow`
5. Accept (y) to run benchmarks

**Expected behavior**
When running the benchmark this will happen

```
=================================================================================================================================================================================
[+] [STEP:8/12] Verifing Tensorflow installation...
=================================================================================================================================================================================
Run Tensorflow benchmark? [Y/n] y

  [+] ⡇ Run Tensorflow Verification...
Traceback (most recent call last):
  File "/home/emoon/RET/benchmarks/tf/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 29, in <module>
    import benchmark_cnn
  File "/home/emoon/RET/benchmarks/tf/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 44, in <module>
    import datasets
  File "/home/emoon/RET/benchmarks/tf/scripts/tf_cnn_benchmarks/datasets.py", line 32, in <module>
    import preprocessing
  File "/home/emoon/RET/benchmarks/tf/scripts/tf_cnn_benchmarks/preprocessing.py", line 28, in <module>
    from tensorflow.contrib.data.python.ops import threadpool
ModuleNotFoundError: No module named 'tensorflow.contrib'
  [+] ⡏ Run resnet50 benchmark...
✘ [ERROR] resnet50 benchmark Failed...[]
```

**Additional context / logs**
I'm pretty sure this is not caused by the installation script but by the the benchmark not being updated but I wanted to report it anyway.

**Comment by reger-men** [comment]
Thanks, @emoon for reporting that!

**tf.contrib** is deprecated in tf 2.0.x and the benchmark/tf-cnn-benchmark folder has not been updated right now. We will maybe use **perfzero** benchmark instead of **tf-cnn-benchmark**.

**Comment by emoon** [comment]
That sounds good :) I think it makes sense to have something like that running so one can do an easy check that everything is working as expected.

**Comment by reger-men** [comment]
We are now using a different repo. It's still simple and has only one model, but we can add new models. However, we can now check the TensorFlow installation.
